# This is a basic workflow to help you get started with Actions

name: CI-build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8' # The JDK version to make available on the path.
          java-package: jre # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64

      # Runs a single command using the runners shell
      - name: Download and install LDDtool version 12.0.0
        run: |
          apk add curl
          cd lib
          curl -O https://github.com/NASA-PDS/pds4-information-model/releases/download/12.0.0/lddtool-12.0.0-bin.tar.gz
          tar -xvzf lddtool-12.0.0-bin.tar.gz
          PATH=${PATH}:`pwd`/bin
          cd ..
      # Runs a set of commands using the runners shell
      - name: Test LDD tool version
        run: |
          lib/lddtool-12.0.0/bin/lddtool -v
          
